---
- name: Install Docker
  hosts: all # We need to docker all hosts
  become: true
  roles:
    - role: "nickjj.docker" # https://github.com/nickjj/ansible-docker
      docker__channel: ["stable"]
      docker__version: "25.0"
      docker__users:
        - "{{ ansible_user_id }}" # Root
        - "{{ ansible_user }}" # ssh user
      tags:
        - docker-init

- name: Install docker swarm on the manager
  hosts: ovh_manager
  become: true
  tasks:
    - name: Swarm
      vars:
        # We use the python interpreter created by the role nickjj.docker.
        # It contains the dependencies we need to init swarm
        ansible_python_interpreter: /usr/local/bin/python3-docker
      tags:
        - swarm
      block:
        - name: Init Swarm cluster address {{ ansible_default_ipv4.interface }}
          community.docker.docker_swarm:
            state: present
            advertise_addr: "{{ ansible_default_ipv4.interface }}"
            task_history_retention_limit: 5
          register: init_swarm_result

        # - name: Swarm init result
        #  debug:
        #    msg: "{{ init_swarm_result }}"

        - name: Install docker_stack module requirements
          ansible.builtin.pip:
            name: "{{ item }}"
          loop:
            - jsondiff
            - pyyaml
