---
- name: Deploy traefik and portainer
  hosts: all
  vars:
    destination_folder: "{{ deployment_path }}/internal"
    domain: reverse-proxy.klivar.com
    ansible_python_interpreter: /usr/local/bin/python3-docker # For docker swarm command
  become: true
  tasks:
    - name: Create destination_folder
      ansible.builtin.file:
        path: "{{ destination_folder }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"
        recurse: true

    - name: Copy traefik file
      ansible.builtin.template:
        src: traefik.yml
        dest: "{{ destination_folder }}/traefik.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"

    - name: Create the network for traefik
      community.docker.docker_network:
        driver: overlay
        name: "{{ traefik_network }}"
        state: present

    - name: Deploy traefik
      community.docker.docker_stack:
        name: traefik
        compose:
          - "{{ destination_folder }}/traefik.yml"
        prune: true
        state: present

    - name: Wait for traefik to be ready
      ansible.builtin.wait_for:
        port: "{{ item }}"
        state: started
        delay: 5
        connect_timeout: 10
        sleep: 5
        timeout: 60
      loop:
        - 80
