---
- name: Deploy traefik
  hosts: all
  vars_files:
    - ./vars/internal-tools.yml
  become: true

  pre_tasks:
    - name: Create the network for traefik
      community.docker.docker_network:
        driver: overlay
        name: "{{ traefik_network }}"
        state: present

  tasks:
    - name: Create destination_folder
      ansible.builtin.file:
        path: "{{ destination_folder }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"
        recurse: true

    - name: Copy traefik file
      ansible.builtin.template:
        src: traefik.yml
        dest: "{{ destination_folder }}/traefik.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"

    - name: Deploy traefik
      community.docker.docker_stack:
        name: traefik
        compose:
          - "{{ destination_folder }}/traefik.yml"
        prune: true
        state: present

    - name: Check if we can access the service
      ansible.builtin.uri:
        url: http://{{ traefik_domain }}
        follow_redirects: true
        force_basic_auth: true
        user: "{{ traefik_basic_auth_user }}"
        password: "{{ traefik_basic_auth_password }}"
        return_content: true
      register: this
      failed_when: "'Traefik' not in this.content or this.status != 200 or 'https://' not in this.url"
      retries: 5
      delay: 5
      until: this.status == 200
