---
- name: Deploy portainer
  hosts: all
  vars_files:
    - ./vars/internal-tools.yml
  become: true
  tasks:
    - name: Create destination_folder
      ansible.builtin.file:
        path: "{{ destination_folder }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"
        recurse: true

    - name: Copy portainer file
      ansible.builtin.template:
        src: portainer.yml
        dest: "{{ destination_folder }}/portainer.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"

    - name: Deploy portainer
      community.docker.docker_stack:
        name: portainer
        compose:
          - "{{ destination_folder }}/portainer.yml"
        prune: true
        state: present

    - name: Check if we can access the service
      ansible.builtin.uri:
        url: http://{{ portainer_domain }}
        follow_redirects: true
        return_content: true
      register: this
      failed_when: "'Portainer' not in this.content or this.status != 200 or 'https://' not in this.url"
