---
- name: Deploy portainer
  hosts: all
  vars_files:
    - ./vars/internal-tools.yml
  become: true
  tasks:
    - name: Create destination_folder
      ansible.builtin.file:
        path: "{{ destination_folder }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"
        recurse: true

    - name: Copy portainer file
      ansible.builtin.template:
        src: portainer.yml
        dest: "{{ destination_folder }}/portainer.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0764"

    - name: Deploy portainer
      community.docker.docker_stack:
        name: portainer
        compose:
          - "{{ destination_folder }}/portainer.yml"
        prune: true
        state: present

    - name: Wait for portainer to be ready
      ansible.builtin.wait_for:
        host: "{{ item.host }}"
        port: "{{ item.port }}"
        state: started
        delay: 5
        connect_timeout: 10
        sleep: 5
        timeout: 60
      loop:
        - port: 9000
          host: "127.0.0.1"
        - port: 443
          host: "{{ portainer_domain }}"

