---
- name: Install some packages and dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    cache_valid_time: 2592000 # 30 jours
  tags:
    - packages

- name: Configuration des locales
  ansible.builtin.import_tasks: locale.yml
  tags:
    - locale

- name: Activation de ntp au démarrage
  ansible.builtin.service:
    name: ntp
    enabled: true

- name: Lancement de ntp
  ansible.builtin.service:
    name: ntp
    state: started
