name: Run a given playbook against the target hosts

on:
  workflow_dispatch:
    inputs:
      playbook-file:
        description: Name of the playbook to run
        required: true
        default: default.yml
        options:
          - default.yml
          - todo.yml
      target:
        description: The target host to run the playbook against from the inventory file
        required: true


jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ansible
        run: |
          ansible --version
          ansible-galaxy install -r requirements.yml --force
